// ignore_for_file: avoid_print
/// Generates a Supabase migration SQL file that upserts all protocols and
/// their research citations from `protocols.json`.
///
/// Usage:
///   dart run tool/generate_seed_sql.dart > supabase/migrations/YYYYMMDDHHMMSS_seed_protocols.sql
///
/// The generated SQL:
/// - Creates a case-insensitive unique index on protocols.name
/// - Upserts each protocol using ON CONFLICT
/// - Deletes then re-inserts citations per protocol
/// - Includes a SHA-256 checksum of protocols.json for audit trail
library;

import 'dart:convert';
import 'dart:io';

void main() {
  final file = File('protocols.json');
  if (!file.existsSync()) {
    stderr.writeln('Error: protocols.json not found in current directory.');
    exit(1);
  }

  final checksum = _sha256File(file.path);
  final rawJson = file.readAsStringSync();
  final protocols = jsonDecode(rawJson) as List<dynamic>;

  final buf = StringBuffer();

  _writeHeader(buf, checksum, protocols.length);
  _writeUniqueIndex(buf);
  _writeProtocolUpserts(buf, protocols);
  _writeCitationInserts(buf, protocols);
  _writeVerificationQueries(buf);

  stdout.write(buf);
}

void _writeHeader(StringBuffer buf, String checksum, int protocolCount) {
  buf.writeln(
    '-- ============================================================================',
  );
  buf.writeln('-- Seed migration: upsert $protocolCount protocols + citations');
  buf.writeln(
    '-- ============================================================================',
  );
  buf.writeln('-- Generated by: dart run tool/generate_seed_sql.dart');
  buf.writeln('-- SHA-256(protocols.json): $checksum');
  buf.writeln(
    '-- ============================================================================',
  );
  buf.writeln();
}

void _writeUniqueIndex(StringBuffer buf) {
  buf.writeln(
    '-- Case-insensitive unique index to support ON CONFLICT upserts',
  );
  buf.writeln(
    'CREATE UNIQUE INDEX IF NOT EXISTS protocols_name_unique '
    'ON public.protocols (lower(name));',
  );
  buf.writeln();
}

void _writeProtocolUpserts(StringBuffer buf, List<dynamic> protocols) {
  buf.writeln(
    '-- ============================================================================',
  );
  buf.writeln('-- PROTOCOL UPSERTS');
  buf.writeln(
    '-- ============================================================================',
  );
  buf.writeln();

  for (final protocol in protocols) {
    final name = protocol['name'] as String;
    final description = protocol['description'] as String;
    final category = protocol['category'] as String;
    final evidenceLevel = protocol['evidence_level'] as String;
    final target = protocol['target'] as Map<String, dynamic>;

    // Build target JSONB — use only the keys the DTO expects:
    // frequency (with min_per_week, max_per_week), durationSeconds, intensity
    final targetJson = jsonEncode(target);

    buf.writeln(
      'INSERT INTO public.protocols '
      '(name, description, target, category, evidence_level)',
    );
    buf.writeln('VALUES (');
    buf.writeln('  ${_dollarQuote(name, 'n')},');
    buf.writeln('  ${_dollarQuote(description, 'desc')},');
    buf.writeln("  '$targetJson'::jsonb,");
    buf.writeln("  '$category',");
    buf.writeln("  '$evidenceLevel'");
    buf.writeln(')');
    buf.writeln('ON CONFLICT ((lower(name))) DO UPDATE SET');
    buf.writeln('  description = EXCLUDED.description,');
    buf.writeln('  target      = EXCLUDED.target,');
    buf.writeln('  category    = EXCLUDED.category,');
    buf.writeln('  evidence_level = EXCLUDED.evidence_level;');
    buf.writeln();
  }
}

void _writeCitationInserts(StringBuffer buf, List<dynamic> protocols) {
  buf.writeln(
    '-- ============================================================================',
  );
  buf.writeln('-- RESEARCH CITATIONS');
  buf.writeln(
    '-- ============================================================================',
  );
  buf.writeln(
    '-- Strategy: delete existing citations per protocol, then re-insert.',
  );
  buf.writeln(
    '-- This ensures citations stay in sync with protocols.json.',
  );
  buf.writeln();

  for (final protocol in protocols) {
    final name = protocol['name'] as String;
    final citations =
        protocol['research_citations'] as List<dynamic>? ?? <dynamic>[];
    if (citations.isEmpty) continue;

    buf.writeln('-- Citations for: $name');
    buf.writeln('DELETE FROM public.research_citations');
    buf.writeln(
      'WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower(${_dollarQuote(name, 'n')}));',
    );
    buf.writeln();

    for (final citation in citations) {
      final authors = citation['authors'] as String;
      final year = citation['year'] as int;
      final title = citation['title'] as String;
      final journal = citation['journal'] as String;
      final doi = citation['doi'] as String?;
      final url = citation['url'] as String?;
      // Deliberately strip verification_status, verification_note, source_models

      buf.writeln(
        'INSERT INTO public.research_citations '
        '(protocol_id, authors, year, title, journal, doi, url)',
      );
      buf.writeln('VALUES (');
      buf.writeln(
        '  (SELECT id FROM public.protocols WHERE lower(name) = lower(${_dollarQuote(name, 'n')})),',
      );
      buf.writeln('  ${_dollarQuote(authors, 'a')},');
      buf.writeln('  $year,');
      buf.writeln('  ${_dollarQuote(title, 't')},');
      buf.writeln('  ${_dollarQuote(journal, 'j')},');
      buf.writeln('  ${doi != null ? _dollarQuote(doi, 'd') : 'null'},');
      buf.writeln('  ${url != null ? _dollarQuote(url, 'u') : 'null'}');
      buf.writeln(');');
      buf.writeln();
    }
  }
}

void _writeVerificationQueries(StringBuffer buf) {
  buf.writeln(
    '-- ============================================================================',
  );
  buf.writeln('-- VERIFICATION QUERIES (can be removed after testing)');
  buf.writeln(
    '-- ============================================================================',
  );
  buf.writeln(
    '-- SELECT COUNT(*) as protocol_count FROM public.protocols;',
  );
  buf.writeln(
    '-- SELECT COUNT(*) as citation_count FROM public.research_citations;',
  );
  buf.writeln(
    '-- SELECT p.name, COUNT(c.id) as citations',
  );
  buf.writeln(
    '--   FROM public.protocols p',
  );
  buf.writeln(
    '--   LEFT JOIN public.research_citations c ON c.protocol_id = p.id',
  );
  buf.writeln(
    '--   GROUP BY p.id, p.name',
  );
  buf.writeln(
    '--   ORDER BY p.name;',
  );
}

/// Computes the SHA-256 checksum of a file by shelling out to `shasum`.
String _sha256File(String path) {
  final result = Process.runSync('shasum', ['-a', '256', path]);
  if (result.exitCode != 0) {
    stderr.writeln('Error computing SHA-256: ${result.stderr}');
    exit(1);
  }
  // Output format: "<hash>  <filename>\n"
  return (result.stdout as String).split(' ').first.trim();
}

/// Wraps [value] in dollar-quoted SQL string: `$tag$value$tag$`.
///
/// The [hint] is used as part of the tag to avoid collisions.
/// If the value contains the tag, a numeric suffix is appended until unique.
String _dollarQuote(String value, String hint) {
  var tag = hint;
  var attempt = 0;
  while (value.contains('\$$tag\$')) {
    attempt++;
    tag = '$hint$attempt';
  }
  return '\$$tag\$$value\$$tag\$';
}
