-- ============================================================================
-- Seed migration: upsert 57 protocols + citations
-- ============================================================================
-- Generated by: dart run tool/generate_seed_sql.dart
-- SHA-256(protocols.json): f117e338d0f94cf0b4a431f3ca85bb705e3ab8f86143bbbdaaff9f2d4ba2bc28
-- ============================================================================

-- Case-insensitive unique index to support ON CONFLICT upserts
CREATE UNIQUE INDEX IF NOT EXISTS protocols_name_unique ON public.protocols (lower(name));

-- ============================================================================
-- PROTOCOL UPSERTS
-- ============================================================================

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Deliberate Cold Water Immersion for Dopamine and Norepinephrine$n$,
  $desc$Immersion in cold water (10–15°C) triggers sustained release of norepinephrine (up to 530%) and dopamine (up to 250%) via sympathetic nervous system activation,  enhancing alertness, mood, and focus for hours post-exposure.$desc$,
  '{"frequency":{"min_per_week":2,"max_per_week":4},"durationSeconds":180,"intensity":"10-15°C"}'::jsonb,
  'coldExposure',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Post-Exercise Cold Water Immersion for Recovery$n$,
  $desc$Cold water immersion at 10–15°C for 10–15 minutes after high-intensity exercise reduces delayed-onset muscle soreness and creatine kinase levels  via vasoconstriction-mediated inflammation reduction and decreased nerve conduction velocity.$desc$,
  '{"frequency":{"min_per_week":1,"max_per_week":4},"durationSeconds":720,"intensity":"10-15°C"}'::jsonb,
  'coldExposure',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Daily Cold Shower for Illness Resilience$n$,
  $desc$Ending a regular shower with 30–90 seconds of cold water activates the sympathetic nervous system  and, when practiced daily for 30+ days, reduces self-reported sickness absence from work by 29%.$desc$,
  '{"frequency":{"min_per_week":5,"max_per_week":7},"durationSeconds":60,"intensity":"10-12°C (coldest tap water)"}'::jsonb,
  'coldExposure',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Regular Cold Exposure for Brown Fat Activation$n$,
  $desc$Repeated brief cold water immersion (0–10°C) activates brown adipose tissue thermogenesis via norepinephrine-mediated β-adrenergic signaling, increasing cold-induced energy expenditure and improving thermoregulatory capacity.$desc$,
  '{"frequency":{"min_per_week":2,"max_per_week":3},"durationSeconds":120,"intensity":"0-10°C (ice water or cold outdoor water)"}'::jsonb,
  'coldExposure',
  'observational'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Finnish Sauna for Cardiovascular Health and Longevity$n$,
  $desc$Regular Finnish dry sauna bathing (80–100°C) improves endothelial function, reduces arterial stiffness, and lowers blood pressure,  with 4–7 sessions per week associated with 50% lower fatal cardiovascular disease risk and 40% lower all-cause mortality over 20 years of follow-up.$desc$,
  '{"frequency":{"min_per_week":4,"max_per_week":7},"durationSeconds":1200,"intensity":"80-100°C (Finnish dry sauna)"}'::jsonb,
  'heatTherapy',
  'observational'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Far-Infrared Sauna for Mood and Depression$n$,
  $desc$Repeated far-infrared sauna sessions at moderate temperature activate thermoregulatory pathways and increase endorphin and serotonin release, reducing depressive symptoms, appetite loss, and somatic complaints in mildly depressed patients.$desc$,
  '{"frequency":{"min_per_week":5,"max_per_week":5},"durationSeconds":900,"intensity":"60°C (far-infrared dry sauna)"}'::jsonb,
  'heatTherapy',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Post-Exercise Sauna for Endurance Enhancement$n$,
  $desc$Sauna bathing immediately after endurance exercise induces heat acclimation adaptations including expanded plasma volume (~7%) and improved oxygen delivery, resulting in meaningful improvements in  VO2max (~8%) and time-to-exhaustion.$desc$,
  '{"frequency":{"min_per_week":3,"max_per_week":4},"durationSeconds":1800,"intensity":"89-101°C (Finnish dry sauna, post-exercise)"}'::jsonb,
  'heatTherapy',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Whole-Body Hyperthermia for Major Depression$n$,
  $desc$A single session raising core body temperature to ~38.5°C stimulates thermoafferent pathways projecting to serotonergic nuclei, producing a rapid antidepressant effect  lasting up to 6 weeks in a double-blind sham-controlled trial.$desc$,
  '{"frequency":{"min_per_week":1,"max_per_week":1},"durationSeconds":2820,"intensity":"Infrared device raising core temperature to 38.5°C"}'::jsonb,
  'heatTherapy',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Zone 2 Sustained Aerobic Training for Metabolic Health$n$,
  $desc$Low-intensity aerobic exercise performed below the lactate threshold  primarily stresses the mitochondrial oxidative system, enhancing fat oxidation capacity, metabolic flexibility, capillary density, and insulin sensitivity for long-term cardiometabolic health.$desc$,
  '{"frequency":{"min_per_week":3,"max_per_week":5},"durationSeconds":2700,"intensity":"Zone 2 (60-70% HRmax, RPE 2-3, blood lactate <2 mmol/L)"}'::jsonb,
  'exercise',
  'observational'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$4x4 High-Intensity Interval Training for VO2max$n$,
  $desc$Four 4-minute intervals at 90–95% maximum heart rate with 3-minute active recovery periods  maximize cardiovascular stress to increase stroke volume and VO2max by ~7%, the strongest independent predictor of cardiovascular health and longevity.$desc$,
  '{"frequency":{"min_per_week":2,"max_per_week":3},"durationSeconds":2100,"intensity":"90-95% HRmax during intervals, 60-70% HRmax during recovery (RPE 7-8)"}'::jsonb,
  'exercise',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Progressive Resistance Training for Longevity$n$,
  $desc$Structured strength training targeting all major muscle groups reduces all-cause mortality by 15–27% through improvements in muscle mass, strength, insulin sensitivity, and bone density, with maximum mortality risk reduction at approximately 60 minutes per week.$desc$,
  '{"frequency":{"min_per_week":2,"max_per_week":3},"durationSeconds":1800,"intensity":"70-85% 1RM (RPE 6-8, 2-4 sets of 8-12 reps per exercise)"}'::jsonb,
  'exercise',
  'observational'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Supramaximal Interval Training for Dual Aerobic-Anaerobic Fitness$n$,
  $desc$Ultra-short supramaximal intervals (8 x 20 seconds all-out with 10-second rest) uniquely improve both aerobic capacity (VO2max +15%) and anaerobic capacity (+28%) simultaneously in just 6 weeks,  despite only 4 minutes of total exercise per session.$desc$,
  '{"frequency":{"min_per_week":3,"max_per_week":4},"durationSeconds":240,"intensity":"RPE 9-10 (maximal effort, ~170% VO2max equivalent)"}'::jsonb,
  'exercise',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Combined Aerobic and Resistance Training for Mortality Reduction$n$,
  $desc$Meeting both aerobic (≥150 min/week moderate) and resistance training (≥2 days/week) guidelines yields a synergistic 40% all-cause mortality reduction,  exceeding either modality alone by targeting complementary cardiovascular, metabolic, and musculoskeletal systems.$desc$,
  '{"frequency":{"min_per_week":4,"max_per_week":5},"durationSeconds":2700,"intensity":"Aerobic: 60-70% HRmax; Resistance: 60-80% 1RM (RPE 5-8)"}'::jsonb,
  'exercise',
  'observational'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Morning Bright Light Exposure for Circadian Entrainment$n$,
  $desc$Exposure to bright light (≥2,000 lux) within 30–60 minutes of waking activates melanopsin-containing retinal ganglion cells and the suprachiasmatic nucleus, advancing circadian phase, strengthening the sleep-wake cycle, and improving sleep onset and daytime alertness.$desc$,
  '{"frequency":{"min_per_week":5,"max_per_week":7},"durationSeconds":1800,"intensity":"≥2,000-10,000 lux within 60 min of waking"}'::jsonb,
  'sleep',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Cool Bedroom Temperature for Sleep Quality$n$,
  $desc$A cool bedroom environment (18–19°C) facilitates the natural 1–2°C core temperature drop required for sleep initiation, supporting deeper slow-wave sleep, fewer nighttime awakenings, and improved overall sleep efficiency.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":28800,"intensity":"18-19°C room temperature"}'::jsonb,
  'sleep',
  'observational'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Sleep Restriction Therapy for Insomnia$n$,
  $desc$Limiting time in bed to match actual sleep time creates mild sleep deprivation that strengthens homeostatic sleep pressure, consolidating sleep and reducing sleep-onset latency and nighttime wakefulness,  with effects comparable to full CBT-I.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":18000,"intensity":"Time in bed = actual sleep time (min 5h), adjust by 15-30 min weekly based on ≥85% sleep efficiency"}'::jsonb,
  'sleep',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Consistent Sleep-Wake Timing Protocol$n$,
  $desc$Maintaining a consistent wake time (±30 minutes daily, including weekends) strengthens circadian entrainment through predictable light and behavioral cues,  with irregular sleep timing associated with poorer sleep quality, metabolic dysfunction, and increased mortality risk.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":60,"intensity":"Wake time variation ≤30 min day-to-day, weekday-weekend ≤1 hour"}'::jsonb,
  'sleep',
  'expertConsensus'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Evening Dim Light Protocol for Melatonin Preservation$n$,
  $desc$Restricting ambient light to <10 lux for 1–2 hours before bedtime preserves endogenous melatonin onset, as ordinary room light (~200 lux) suppresses melatonin production by up to 71% and shortens melatonin duration by ~90 minutes.$desc$,
  '{"frequency":{"min_per_week":5,"max_per_week":7},"durationSeconds":5400,"intensity":"<10 lux ambient light 1-2 hours before bed"}'::jsonb,
  'sleep',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Time-Restricted Eating for Metabolic Health$n$,
  $desc$Confining all daily caloric intake to an 8–10 hour window with 14–16 hours fasting  promotes weight loss, improved glucose regulation, and reduced blood pressure by leveraging fasting-mediated metabolic switching from glycogen to fat oxidation.$desc$,
  '{"frequency":{"min_per_week":5,"max_per_week":7},"durationSeconds":1,"intensity":"8-10 hour eating window"}'::jsonb,
  'nutrition',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Mediterranean Dietary Pattern for Cardiovascular Protection$n$,
  $desc$A whole-diet pattern emphasizing extra-virgin olive oil, vegetables, fruits, nuts, legumes, and fish  reduces major cardiovascular events by ~30%  through anti-inflammatory, antioxidant, and lipid-modifying mechanisms as demonstrated in the PREDIMED trial.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":1,"intensity":"14-point Mediterranean adherence score ≥9; ≥4 tbsp EVOO/day, ≥3 servings fruit/day"}'::jsonb,
  'nutrition',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$High-Protein Intake for Body Composition$n$,
  $desc$Increasing daily protein intake to 1.6–2.2 g/kg body weight during resistance training enhances lean mass accretion and strength gains, with a meta-analytic breakpoint at 1.62 g/kg/day beyond which no further fat-free mass benefits were observed.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":1,"intensity":"1.6-2.2g protein/kg/day distributed across 3-4 meals"}'::jsonb,
  'nutrition',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Peri-Workout Protein for Muscle Protein Synthesis$n$,
  $desc$Consuming 20–40g protein within ~2 hours of resistance exercise supports muscle protein synthesis, though meta-analytic evidence indicates total daily protein intake is the primary driver of muscular adaptations rather than precise timing.$desc$,
  '{"frequency":{"min_per_week":3,"max_per_week":6},"durationSeconds":1,"intensity":"20-40g protein (≥0.4g/kg) within 2 hours pre- or post-exercise"}'::jsonb,
  'nutrition',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Early Time-Restricted Eating for Insulin Sensitivity$n$,
  $desc$Restricting the eating window to early daytime hours (ending by 3–4 PM) aligns food intake with circadian peaks in insulin sensitivity and β-cell responsiveness, improving blood pressure, oxidative stress, and metabolic markers even without weight loss.$desc$,
  '{"frequency":{"min_per_week":5,"max_per_week":7},"durationSeconds":1,"intensity":"6-8 hour eating window ending by 3-4 PM"}'::jsonb,
  'nutrition',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Creatine Monohydrate for Strength and Cognition$n$,
  $desc$Creatine monohydrate replenishes ATP in muscle and brain tissue, enhancing muscular strength and power output while improving memory, processing speed, and attention, particularly under conditions of mental fatigue or in older adults.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":60,"intensity":"5g daily with water or meal"}'::jsonb,
  'supplements',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Omega-3 EPA/DHA for Cardiovascular Health$n$,
  $desc$Long-chain omega-3 fatty acids reduce triglycerides, lower blood pressure, and decrease systemic inflammation, with dose-dependent reductions in myocardial infarction risk (13%), coronary heart disease events (10%), and cardiovascular mortality (7%).$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":60,"intensity":"1000-3000mg combined EPA/DHA daily with fat-containing meal"}'::jsonb,
  'supplements',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Vitamin D3 for Immune Function and Cancer Mortality Reduction$n$,
  $desc$Vitamin D3 supplementation corrects widespread deficiency (~40% of adults), supports immune and bone health, and reduces cancer mortality by 16% in meta-analyses of RCTs, with 2,000–5,000 IU daily sufficient to maintain optimal serum levels.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":60,"intensity":"2000-5000 IU (50-125µg) daily with fat-containing meal"}'::jsonb,
  'supplements',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Magnesium Supplementation for Sleep Quality$n$,
  $desc$Magnesium acts as a natural NMDA receptor antagonist and GABA agonist, reducing sleep onset latency by ~17 minutes, increasing melatonin levels, and decreasing cortisol when supplemented before bed in older adults.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":60,"intensity":"200-400mg elemental magnesium (glycinate or threonate) 30-60 min before bed"}'::jsonb,
  'supplements',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Ashwagandha Root Extract for Stress and Cortisol Reduction$n$,
  $desc$Ashwagandha’s withanolides modulate the hypothalamic-pituitary-adrenal axis and exert GABAergic activity, significantly reducing serum cortisol levels and perceived stress scores in a dose-dependent manner across multiple RCTs.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":60,"intensity":"300-600mg standardized root extract (≥5% withanolides) daily with food"}'::jsonb,
  'supplements',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Mindfulness-Based Stress Reduction Program$n$,
  $desc$An 8-week structured program combining seated meditation, body scanning, and gentle yoga that cultivates present-moment awareness, producing moderate effects (Hedge’s g = 0.53) on stress, anxiety, depression, and quality of life.$desc$,
  '{"frequency":{"min_per_week":6,"max_per_week":7},"durationSeconds":2700,"intensity":"Guided meditation + body scan + gentle yoga (instructor-led 8-week program)"}'::jsonb,
  'mind',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Guided Body Scan Deep Relaxation$n$,
  $desc$A guided meditation performed lying down that systematically directs awareness through the body to induce deep parasympathetic relaxation while maintaining consciousness, reducing stress and improving sleep quality and well-being.$desc$,
  '{"frequency":{"min_per_week":3,"max_per_week":7},"durationSeconds":660,"intensity":"Guided audio body scan + breath awareness (lying down)"}'::jsonb,
  'mind',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Cyclic Sighing Breathwork for Mood Enhancement$n$,
  $desc$A structured breathing technique (double nasal inhale followed by prolonged oral exhale) activates the parasympathetic nervous system via respiratory sinus arrhythmia, producing greater improvement in positive affect than mindfulness meditation in just 5 minutes daily.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":300,"intensity":"Self-guided cyclic sighing (double inhale nose, long exhale mouth)"}'::jsonb,
  'mind',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Structured Gratitude Journaling for Well-Being$n$,
  $desc$Listing 3–5 things one is grateful for with brief reflection shifts attentional focus toward positive experiences through cognitive reappraisal, enhancing positive affect, life satisfaction, and subjective well-being (Hedges’ g = 0.22 across 25 RCTs).$desc$,
  '{"frequency":{"min_per_week":3,"max_per_week":7},"durationSeconds":600,"intensity":"Self-guided structured writing (3-5 items with reflection)"}'::jsonb,
  'mind',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Focused Attention Meditation for Cognitive Enhancement$n$,
  $desc$Sustained concentration on a single object (typically the breath) while redirecting attention from distractions strengthens executive control and attention networks, producing small-to-moderate improvements in working memory, sustained attention, and cognitive flexibility.$desc$,
  '{"frequency":{"min_per_week":3,"max_per_week":7},"durationSeconds":900,"intensity":"Guided or unguided single-point breath concentration"}'::jsonb,
  'mind',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$14°C Cold Water Immersion for Catecholamine Response$n$,
  $desc$Immersion in cold water (~14°C) can acutely increase plasma norepinephrine and dopamine, which may transiently boost alertness and support stress resilience via sympathetic activation.$desc$,
  '{"frequency":{"min_per_week":1,"max_per_week":3},"durationSeconds":1200,"intensity":"14°C"}'::jsonb,
  'coldExposure',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Post-Exercise Cold Water Immersion for Soreness and Recovery$n$,
  $desc$Cold water immersion after strenuous exercise can reduce delayed-onset muscle soreness and perceived fatigue, likely via reduced tissue temperature and modulation of inflammatory signaling.$desc$,
  '{"frequency":{"min_per_week":2,"max_per_week":4},"durationSeconds":600,"intensity":"10-15°C"}'::jsonb,
  'coldExposure',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Daily Cold-Shower Finish for Sickness Absence Reduction$n$,
  $desc$A brief cold-shower finish applied daily is a repeatable mild stressor that has been associated with reduced sickness absence from work, potentially via improved stress tolerance and immune-related effects.$desc$,
  '{"frequency":{"min_per_week":5,"max_per_week":7},"durationSeconds":60,"intensity":"10-15°C (cold shower)"}'::jsonb,
  'coldExposure',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Frequent Finnish Sauna Bathing for Cardiovascular Risk Reduction$n$,
  $desc$Higher sauna frequency is associated with lower risks of fatal cardiovascular events and all-cause mortality in cohort data, potentially via improved vascular function, blood pressure, and cardiometabolic resilience.$desc$,
  '{"frequency":{"min_per_week":4,"max_per_week":7},"durationSeconds":1200,"intensity":"80-100°C (Finnish dry)"}'::jsonb,
  'heatTherapy',
  'observational'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Post-Exercise Sauna Bathing for Endurance Adaptation$n$,
  $desc$Adding sauna exposure after endurance training can improve time-to-exhaustion performance, plausibly through heat-driven plasma volume expansion and thermoregulatory adaptations.$desc$,
  '{"frequency":{"min_per_week":3,"max_per_week":5},"durationSeconds":1800,"intensity":"85-95°C (sauna)"}'::jsonb,
  'heatTherapy',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Single-Session Whole-Body Hyperthermia for Depressive Symptoms$n$,
  $desc$A single whole-body hyperthermia session has shown antidepressant effects lasting weeks, potentially via thermoregulatory, inflammatory, and neuroendocrine pathways; this should be done under appropriate clinical supervision.$desc$,
  '{"frequency":{"min_per_week":1,"max_per_week":1},"durationSeconds":3600,"intensity":"55-65°C (whole-body hyperthermia; target core temp ~38.5°C)"}'::jsonb,
  'heatTherapy',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Zone 2 Continuous Endurance Training for Aerobic Base$n$,
  $desc$Regular moderate-intensity continuous training improves aerobic capacity and VO2max, supporting mitochondrial and cardiometabolic health with a sustainable stimulus.$desc$,
  '{"frequency":{"min_per_week":3,"max_per_week":5},"durationSeconds":2700,"intensity":"Zone 2 (60-70% HRmax)"}'::jsonb,
  'exercise',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$4x4 Minute HIIT for VO2max$n$,
  $desc$High-intensity intervals performed near 90-95% HRmax provide a strong VO2max stimulus and cardiovascular adaptation with relatively low total work time.$desc$,
  '{"frequency":{"min_per_week":2,"max_per_week":3},"durationSeconds":2400,"intensity":"4×4 min at 90-95% HRmax (3 min easy between)"}'::jsonb,
  'exercise',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Sprint Interval Training for Mitochondrial and Cardiometabolic Adaptation$n$,
  $desc$Very short all-out intervals with long recoveries can drive rapid improvements in skeletal muscle oxidative capacity and cardiometabolic fitness with low total training time.$desc$,
  '{"frequency":{"min_per_week":2,"max_per_week":3},"durationSeconds":1200,"intensity":"All-out (RPE 9-10)"}'::jsonb,
  'exercise',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Progressive Full-Body Resistance Training for Strength and Functional Longevity$n$,
  $desc$Progressive resistance training improves muscular strength in older adults, supporting functional independence and metabolic health via muscle hypertrophy and neuromuscular adaptation.$desc$,
  '{"frequency":{"min_per_week":2,"max_per_week":3},"durationSeconds":2700,"intensity":"60-80% 1RM (2-3 sets × 8-12 reps)"}'::jsonb,
  'exercise',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Morning Bright-Light Exposure for Circadian Alignment$n$,
  $desc$Timed bright-light exposure strengthens circadian entrainment and can improve sleep outcomes by reinforcing the morning light signal that sets daily biological timing.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":1800,"intensity":"≥2,500-10,000 lux within 1 hour of waking"}'::jsonb,
  'sleep',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Evening Blue-Light Blocking to Improve Insomnia Symptoms$n$,
  $desc$Reducing blue-rich light exposure in the evening can support melatonin signaling and improve sleep in insomnia by lowering the circadian-disrupting effect of nighttime light.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":7200,"intensity":"<50 lux blue-rich light; blue-blocking glasses 2-3h pre-bed"}'::jsonb,
  'sleep',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Warm Bath or Shower 1-2 Hours Before Bed to Shorten Sleep Onset$n$,
  $desc$Passive body heating before bed can improve sleep onset and sleep efficiency by enhancing the post-bath drop in core temperature and increasing heat loss from the periphery.$desc$,
  '{"frequency":{"min_per_week":5,"max_per_week":7},"durationSeconds":600,"intensity":"40-42.5°C water, timed 1-2h before bed"}'::jsonb,
  'sleep',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Sleep Restriction Therapy for Chronic Insomnia$n$,
  $desc$Sleep restriction therapy consolidates sleep by limiting time in bed to increase homeostatic sleep drive and reduce fragmented, wakeful time, improving insomnia severity over time.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":21600,"intensity":"Time in bed = average sleep time +30 min (min 5h), adjust weekly by sleep efficiency"}'::jsonb,
  'sleep',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Early Time-Restricted Eating Window for Insulin Sensitivity$n$,
  $desc$Restricting food intake to an early-day window can improve insulin sensitivity and cardiometabolic markers even without weight loss, aligning eating with circadian metabolic rhythms.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":21600,"intensity":"6-hour eating window ending before 15:00 (e.g., 08:00-14:00)"}'::jsonb,
  'nutrition',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Mediterranean Dietary Pattern With Olive Oil or Nuts for Cardiovascular Prevention$n$,
  $desc$A Mediterranean dietary pattern supplemented with extra-virgin olive oil or mixed nuts reduced major cardiovascular events in a large randomized trial, likely via improvements in lipids, inflammation, and endothelial function.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":86400,"intensity":"Mediterranean pattern; add ~30 g mixed nuts/day or ~1 L/week extra-virgin olive oil"}'::jsonb,
  'nutrition',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Post-Exercise Carbohydrate+Protein Feeding for Glycogen Recovery$n$,
  $desc$Consuming carbohydrate with added protein soon after exercise can enhance muscle glycogen resynthesis compared with carbohydrate alone, supporting recovery when training sessions are frequent.$desc$,
  '{"frequency":{"min_per_week":2,"max_per_week":6},"durationSeconds":1800,"intensity":"Carb 0.8-1.2 g/kg + protein 0.2-0.4 g/kg within 2h post-exercise"}'::jsonb,
  'nutrition',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Nightly Magnesium Supplementation for Primary Insomnia$n$,
  $desc$Magnesium may support sleep regulation via effects on GABAergic and NMDA-related signaling; supplementation improved subjective and objective insomnia measures in an elderly insomnia trial.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":60,"intensity":"500 mg magnesium daily, taken 1-2h before bed (8 weeks)"}'::jsonb,
  'supplements',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Daily Creatine Monohydrate for Strength and Lean Mass$n$,
  $desc$Creatine monohydrate increases intramuscular phosphocreatine availability, improving high-intensity performance and supporting greater lean mass gains when paired with training; safety and efficacy are supported across many trials.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":60,"intensity":"3-5 g creatine monohydrate daily with meal (optional loading 20 g/day × 5-7 days)"}'::jsonb,
  'supplements',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Daily Omega-3 EPA+DHA for Lipid and Cardiovascular Risk Markers$n$,
  $desc$EPA/DHA supplementation can improve cardiovascular risk factors (including triglycerides) across randomized trials and meta-analyses, likely via effects on lipid metabolism and inflammatory pathways.$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":60,"intensity":"1-4 g/day EPA+DHA with meals"}'::jsonb,
  'supplements',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Ashwagandha Root Extract for Stress and Anxiety Reduction$n$,
  $desc$Ashwagandha root extract has reduced perceived stress and anxiety measures in randomized trials, plausibly via adaptogenic effects on stress-response physiology (including cortisol).$desc$,
  '{"frequency":{"min_per_week":7,"max_per_week":7},"durationSeconds":60,"intensity":"300 mg twice daily (root extract) with meals for 60 days"}'::jsonb,
  'supplements',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Mindfulness-Based Stress Reduction Daily Practice$n$,
  $desc$Mindfulness-based stress reduction (MBSR) improves stress-related outcomes across populations, likely by strengthening attention regulation, present-moment awareness, and emotion regulation skills.$desc$,
  '{"frequency":{"min_per_week":6,"max_per_week":7},"durationSeconds":2700,"intensity":"guided mindfulness (MBSR-style body scan/sitting meditation)"}'::jsonb,
  'mind',
  'multipleRcts'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Cyclic Sighing Breathwork for Acute Mood and Arousal Reduction$n$,
  $desc$Brief daily structured breathing (including cyclic sighing) can improve mood and reduce physiological arousal, likely via vagal engagement and altered respiratory chemistry.$desc$,
  '{"frequency":{"min_per_week":5,"max_per_week":7},"durationSeconds":300,"intensity":"cyclic sighing (double inhale + long slow exhale)"}'::jsonb,
  'mind',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

INSERT INTO public.protocols (name, description, target, category, evidence_level)
VALUES (
  $n$Structured Gratitude Journaling for Well-Being$n$,
  $desc$Structured gratitude listing can improve subjective well-being and positive affect by systematically directing attention toward positive experiences and supportive relationships.$desc$,
  '{"frequency":{"min_per_week":1,"max_per_week":3},"durationSeconds":600,"intensity":"write 5 specific gratitudes (structured list)"}'::jsonb,
  'mind',
  'singleRct'
)
ON CONFLICT ((lower(name))) DO UPDATE SET
  description = EXCLUDED.description,
  target      = EXCLUDED.target,
  category    = EXCLUDED.category,
  evidence_level = EXCLUDED.evidence_level;

-- ============================================================================
-- RESEARCH CITATIONS
-- ============================================================================
-- Strategy: delete existing citations per protocol, then re-insert.
-- This ensures citations stay in sync with protocols.json.

-- Citations for: Deliberate Cold Water Immersion for Dopamine and Norepinephrine
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Deliberate Cold Water Immersion for Dopamine and Norepinephrine$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Deliberate Cold Water Immersion for Dopamine and Norepinephrine$n$)),
  $a$Srámek, Simecková, Janský, Savlíková, Vybíral$a$,
  2000,
  $t$Human physiological responses to immersion into water of different temperatures$t$,
  $j$European Journal of Applied Physiology$j$,
  $d$10.1007/s004210050065$d$,
  $u$https://doi.org/10.1007/s004210050065$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Deliberate Cold Water Immersion for Dopamine and Norepinephrine$n$)),
  $a$Leppäluoto, Westerlund, Huttunen, Oksa, Smolander, Dugué, Mikkelsson$a$,
  2008,
  $t$Effects of long-term whole-body cold exposures on plasma concentrations of ACTH, beta-endorphin, cortisol, catecholamines and cytokines in healthy females$t$,
  $j$Scandinavian Journal of Clinical and Laboratory Investigation$j$,
  $d$10.1080/00365510701516350$d$,
  $u$https://doi.org/10.1080/00365510701516350$u$
);

-- Citations for: Post-Exercise Cold Water Immersion for Recovery
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Cold Water Immersion for Recovery$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Cold Water Immersion for Recovery$n$)),
  $a$Moore, Fuller, Buckley, Saunders, Halson, Broatch, Bellenger$a$,
  2022,
  $t$Impact of Cold-Water Immersion Compared with Passive Recovery Following a Single Bout of Strenuous Exercise on Athletic Performance in Physically Active Participants: A Systematic Review with Meta-analysis and Meta-regression$t$,
  $j$Sports Medicine$j$,
  $d$10.1007/s40279-022-01644-9$d$,
  $u$https://doi.org/10.1007/s40279-022-01644-9$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Cold Water Immersion for Recovery$n$)),
  $a$Xiao, Kabachkova, Jiao, Zhao, Kapilevich$a$,
  2023,
  $t$Effects of cold water immersion after exercise on fatigue recovery and exercise performance—meta analysis$t$,
  $j$Frontiers in Physiology$j$,
  $d$10.3389/fphys.2023.1006512$d$,
  $u$https://doi.org/10.3389/fphys.2023.1006512$u$
);

-- Citations for: Daily Cold Shower for Illness Resilience
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Daily Cold Shower for Illness Resilience$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Daily Cold Shower for Illness Resilience$n$)),
  $a$Buijze, Sierevelt, van der Heijden, Dijkgraaf, Frings-Dresen$a$,
  2016,
  $t$The Effect of Cold Showering on Health and Work: A Randomized Controlled Trial$t$,
  $j$PLoS ONE$j$,
  $d$10.1371/journal.pone.0161749$d$,
  $u$https://doi.org/10.1371/journal.pone.0161749$u$
);

-- Citations for: Regular Cold Exposure for Brown Fat Activation
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Regular Cold Exposure for Brown Fat Activation$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Regular Cold Exposure for Brown Fat Activation$n$)),
  $a$Søberg, Löfgren, Philipsen, Jensen, Hansen, Ahrens, Nystrup, Nielsen, Sølling, Wedell-Neergaard, Berntsen, Loft, Kjær, Gerhart-Hines, Johannesen, Pedersen, Karstoft, Scheele$a$,
  2021,
  $t$Altered brown fat thermoregulation and enhanced cold-induced thermogenesis in young, healthy, winter-swimming men$t$,
  $j$Cell Reports Medicine$j$,
  $d$10.1016/j.xcrm.2021.100408$d$,
  $u$https://doi.org/10.1016/j.xcrm.2021.100408$u$
);

-- Citations for: Finnish Sauna for Cardiovascular Health and Longevity
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Finnish Sauna for Cardiovascular Health and Longevity$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Finnish Sauna for Cardiovascular Health and Longevity$n$)),
  $a$Laukkanen, Khan, Zaccardi, Laukkanen$a$,
  2015,
  $t$Association Between Sauna Bathing and Fatal Cardiovascular and All-Cause Mortality Events$t$,
  $j$JAMA Internal Medicine$j$,
  $d$10.1001/jamainternmed.2014.8187$d$,
  $u$https://doi.org/10.1001/jamainternmed.2014.8187$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Finnish Sauna for Cardiovascular Health and Longevity$n$)),
  $a$Laukkanen, Kunutsor, Khan, et al.$a$,
  2018,
  $t$Sauna bathing is associated with reduced cardiovascular mortality and improves risk prediction in men and women: a prospective cohort study$t$,
  $j$BMC Medicine$j$,
  $d$10.1186/s12916-018-1198-0$d$,
  $u$https://doi.org/10.1186/s12916-018-1198-0$u$
);

-- Citations for: Far-Infrared Sauna for Mood and Depression
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Far-Infrared Sauna for Mood and Depression$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Far-Infrared Sauna for Mood and Depression$n$)),
  $a$Masuda, Nakazato, Kihara, Minagoe, Tei$a$,
  2005,
  $t$Repeated Thermal Therapy Diminishes Appetite Loss and Subjective Complaints in Mildly Depressed Patients$t$,
  $j$Psychosomatic Medicine$j$,
  $d$10.1097/01.psy.0000171812.67767.8f$d$,
  $u$https://doi.org/10.1097/01.psy.0000171812.67767.8f$u$
);

-- Citations for: Post-Exercise Sauna for Endurance Enhancement
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Sauna for Endurance Enhancement$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Sauna for Endurance Enhancement$n$)),
  $a$Scoon, Hopkins, Mayhew, Cotter$a$,
  2007,
  $t$Effect of post-exercise sauna bathing on the endurance performance of competitive male runners$t$,
  $j$Journal of Science and Medicine in Sport$j$,
  $d$10.1016/j.jsams.2006.06.009$d$,
  $u$https://doi.org/10.1016/j.jsams.2006.06.009$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Sauna for Endurance Enhancement$n$)),
  $a$Kirby, Lucas, Armstrong, Weaver, Lucas$a$,
  2021,
  $t$Intermittent post-exercise sauna bathing improves markers of exercise capacity in hot and temperate conditions in trained middle-distance runners$t$,
  $j$European Journal of Applied Physiology$j$,
  $d$10.1007/s00421-020-04541-z$d$,
  $u$https://doi.org/10.1007/s00421-020-04541-z$u$
);

-- Citations for: Whole-Body Hyperthermia for Major Depression
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Whole-Body Hyperthermia for Major Depression$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Whole-Body Hyperthermia for Major Depression$n$)),
  $a$Janssen, Lowry, Mehl, Allen, Kelly, Gartner, Medrano, Begay, Rentscher, White, Fridman, Roberts, Robbins, Hanusch, Cole, Raison$a$,
  2016,
  $t$Whole-Body Hyperthermia for the Treatment of Major Depressive Disorder: A Randomized Clinical Trial$t$,
  $j$JAMA Psychiatry$j$,
  $d$10.1001/jamapsychiatry.2016.1031$d$,
  $u$https://doi.org/10.1001/jamapsychiatry.2016.1031$u$
);

-- Citations for: Zone 2 Sustained Aerobic Training for Metabolic Health
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Zone 2 Sustained Aerobic Training for Metabolic Health$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Zone 2 Sustained Aerobic Training for Metabolic Health$n$)),
  $a$San-Millán, Brooks$a$,
  2018,
  $t$Assessment of Metabolic Flexibility by Means of Measuring Blood Lactate, Fat, and Carbohydrate Oxidation Responses to Exercise in Professional Endurance Athletes and Less-Fit Individuals$t$,
  $j$Sports Medicine$j$,
  $d$10.1007/s40279-017-0751-x$d$,
  $u$https://doi.org/10.1007/s40279-017-0751-x$u$
);

-- Citations for: 4x4 High-Intensity Interval Training for VO2max
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$4x4 High-Intensity Interval Training for VO2max$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$4x4 High-Intensity Interval Training for VO2max$n$)),
  $a$Helgerud, Høydal, Wang, Karlsen, Berg, Bjerkaas, Simonsen, Helgesen, Hjorth, Bach, Hoff$a$,
  2007,
  $t$Aerobic high-intensity intervals improve VO2max more than moderate training$t$,
  $j$Medicine & Science in Sports & Exercise$j$,
  $d$10.1249/mss.0b013e3180304570$d$,
  $u$https://doi.org/10.1249/mss.0b013e3180304570$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$4x4 High-Intensity Interval Training for VO2max$n$)),
  $a$Rognmo, Hetland, Helgerud, Hoff, Slørdahl$a$,
  2004,
  $t$High intensity aerobic interval exercise is superior to moderate intensity exercise for increasing aerobic capacity in patients with coronary artery disease$t$,
  $j$European Journal of Cardiovascular Prevention & Rehabilitation$j$,
  $d$10.1097/01.hjr.0000131677.96762.0c$d$,
  $u$https://doi.org/10.1097/01.hjr.0000131677.96762.0c$u$
);

-- Citations for: Progressive Resistance Training for Longevity
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Progressive Resistance Training for Longevity$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Progressive Resistance Training for Longevity$n$)),
  $a$Shailendra, Baldock, Li, Bennie, Boyle$a$,
  2022,
  $t$Resistance Training and Mortality Risk: A Systematic Review and Meta-Analysis$t$,
  $j$American Journal of Preventive Medicine$j$,
  $d$10.1016/j.amepre.2022.03.020$d$,
  $u$https://doi.org/10.1016/j.amepre.2022.03.020$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Progressive Resistance Training for Longevity$n$)),
  $a$Saeidifard, Medina-Inojosa, West, et al.$a$,
  2019,
  $t$The association of resistance training with mortality: a systematic review and meta-analysis$t$,
  $j$European Journal of Preventive Cardiology$j$,
  $d$10.1177/2047487319850718$d$,
  $u$https://doi.org/10.1177/2047487319850718$u$
);

-- Citations for: Supramaximal Interval Training for Dual Aerobic-Anaerobic Fitness
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Supramaximal Interval Training for Dual Aerobic-Anaerobic Fitness$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Supramaximal Interval Training for Dual Aerobic-Anaerobic Fitness$n$)),
  $a$Tabata, Nishimura, Kouzaki, Hirai, Ogita, Miyachi, Yamamoto$a$,
  1996,
  $t$Effects of moderate-intensity endurance and high-intensity intermittent training on anaerobic capacity and VO2max$t$,
  $j$Medicine and Science in Sports and Exercise$j$,
  $d$10.1097/00005768-199610000-00018$d$,
  $u$https://doi.org/10.1097/00005768-199610000-00018$u$
);

-- Citations for: Combined Aerobic and Resistance Training for Mortality Reduction
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Combined Aerobic and Resistance Training for Mortality Reduction$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Combined Aerobic and Resistance Training for Mortality Reduction$n$)),
  $a$Zhao, Veeranki, Magnussen, Xi$a$,
  2020,
  $t$Recommended physical activity and all cause and cause specific mortality in US adults: prospective cohort study$t$,
  $j$BMJ$j$,
  $d$10.1136/bmj.m2031$d$,
  $u$https://doi.org/10.1136/bmj.m2031$u$
);

-- Citations for: Morning Bright Light Exposure for Circadian Entrainment
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Morning Bright Light Exposure for Circadian Entrainment$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Morning Bright Light Exposure for Circadian Entrainment$n$)),
  $a$Blume, Garbazza, Spitschan$a$,
  2019,
  $t$Effects of light on human circadian rhythms, sleep and mood$t$,
  $j$Somnologie$j$,
  $d$10.1007/s11818-019-00215-x$d$,
  $u$https://doi.org/10.1007/s11818-019-00215-x$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Morning Bright Light Exposure for Circadian Entrainment$n$)),
  $a$Crowley, Eastman$a$,
  2015,
  $t$Phase advancing human circadian rhythms with morning bright light, afternoon melatonin, and gradually shifted sleep: can we reduce morning bright-light duration?$t$,
  $j$Sleep Medicine$j$,
  $d$10.1016/j.sleep.2014.12.004$d$,
  $u$https://doi.org/10.1016/j.sleep.2014.12.004$u$
);

-- Citations for: Cool Bedroom Temperature for Sleep Quality
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Cool Bedroom Temperature for Sleep Quality$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Cool Bedroom Temperature for Sleep Quality$n$)),
  $a$Baniassadi, Manor, Yu, Travison, Lipsitz$a$,
  2023,
  $t$Nighttime ambient temperature and sleep in community-dwelling older adults$t$,
  $j$Science of the Total Environment$j$,
  $d$10.1016/j.scitotenv.2023.165623$d$,
  $u$https://doi.org/10.1016/j.scitotenv.2023.165623$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Cool Bedroom Temperature for Sleep Quality$n$)),
  $a$Harding, Franks, Wisden$a$,
  2019,
  $t$The Temperature Dependence of Sleep$t$,
  $j$Frontiers in Neuroscience$j$,
  $d$10.3389/fnins.2019.00336$d$,
  $u$https://doi.org/10.3389/fnins.2019.00336$u$
);

-- Citations for: Sleep Restriction Therapy for Insomnia
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Sleep Restriction Therapy for Insomnia$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Sleep Restriction Therapy for Insomnia$n$)),
  $a$Maurer, Schneider, Miller, Espie, Kyle$a$,
  2021,
  $t$The clinical effects of sleep restriction therapy for insomnia: A meta-analysis of randomised controlled trials$t$,
  $j$Sleep Medicine Reviews$j$,
  $d$10.1016/j.smrv.2021.101493$d$,
  $u$https://doi.org/10.1016/j.smrv.2021.101493$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Sleep Restriction Therapy for Insomnia$n$)),
  $a$Kyle, Siriwardena, Espie, et al.$a$,
  2023,
  $t$Clinical and cost-effectiveness of nurse-delivered sleep restriction therapy for insomnia in primary care (HABIT): a pragmatic, superiority, open-label, randomised controlled trial$t$,
  $j$The Lancet$j$,
  $d$10.1016/S0140-6736(23)00683-9$d$,
  $u$https://doi.org/10.1016/S0140-6736(23)00683-9$u$
);

-- Citations for: Consistent Sleep-Wake Timing Protocol
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Consistent Sleep-Wake Timing Protocol$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Consistent Sleep-Wake Timing Protocol$n$)),
  $a$Sletten, Weaver, Foster, Gozal, Klerman, Rajaratnam, Roenneberg, Takahashi, Turek, Vitiello, Young, Czeisler$a$,
  2023,
  $t$The importance of sleep regularity: a consensus statement of the National Sleep Foundation sleep timing and variability panel$t$,
  $j$Sleep Health$j$,
  $d$10.1016/j.sleh.2023.07.016$d$,
  $u$https://doi.org/10.1016/j.sleh.2023.07.016$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Consistent Sleep-Wake Timing Protocol$n$)),
  $a$Chaput, Dutil, Featherstone, Ross, Giangregorio, Saunders, Janssen, Poitras, Kho, Ross-White, Zankar, Carrier$a$,
  2020,
  $t$Sleep timing, sleep consistency, and health in adults: a systematic review$t$,
  $j$Applied Physiology, Nutrition, and Metabolism$j$,
  $d$10.1139/apnm-2020-0032$d$,
  $u$https://doi.org/10.1139/apnm-2020-0032$u$
);

-- Citations for: Evening Dim Light Protocol for Melatonin Preservation
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Evening Dim Light Protocol for Melatonin Preservation$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Evening Dim Light Protocol for Melatonin Preservation$n$)),
  $a$Gooley, Chamberlain, Smith, Khalsa, Rajaratnam, Van Reen, Zeitzer, Czeisler, Lockley$a$,
  2011,
  $t$Exposure to room light before bedtime suppresses melatonin onset and shortens melatonin duration in humans$t$,
  $j$The Journal of Clinical Endocrinology & Metabolism$j$,
  $d$10.1210/jc.2010-2098$d$,
  $u$https://doi.org/10.1210/jc.2010-2098$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Evening Dim Light Protocol for Melatonin Preservation$n$)),
  $a$Burgess, Molina$a$,
  2014,
  $t$Home lighting before usual bedtime impacts circadian timing: a field study$t$,
  $j$Photochemistry and Photobiology$j$,
  $d$10.1111/php.12241$d$,
  $u$https://doi.org/10.1111/php.12241$u$
);

-- Citations for: Time-Restricted Eating for Metabolic Health
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Time-Restricted Eating for Metabolic Health$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Time-Restricted Eating for Metabolic Health$n$)),
  $a$Liu, Huang, Huang, et al.$a$,
  2022,
  $t$Calorie Restriction with or without Time-Restricted Eating in Weight Loss$t$,
  $j$New England Journal of Medicine$j$,
  $d$10.1056/NEJMoa2114833$d$,
  $u$https://doi.org/10.1056/NEJMoa2114833$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Time-Restricted Eating for Metabolic Health$n$)),
  $a$Xie, Sun, Ye, et al.$a$,
  2022,
  $t$Randomized controlled trial for time-restricted eating in healthy volunteers without obesity$t$,
  $j$Nature Communications$j$,
  $d$10.1038/s41467-022-28662-5$d$,
  $u$https://doi.org/10.1038/s41467-022-28662-5$u$
);

-- Citations for: Mediterranean Dietary Pattern for Cardiovascular Protection
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Mediterranean Dietary Pattern for Cardiovascular Protection$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Mediterranean Dietary Pattern for Cardiovascular Protection$n$)),
  $a$Estruch, Ros, Salas-Salvadó, et al.$a$,
  2018,
  $t$Primary Prevention of Cardiovascular Disease with a Mediterranean Diet Supplemented with Extra-Virgin Olive Oil or Nuts$t$,
  $j$New England Journal of Medicine$j$,
  $d$10.1056/NEJMoa1800389$d$,
  $u$https://doi.org/10.1056/NEJMoa1800389$u$
);

-- Citations for: High-Protein Intake for Body Composition
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$High-Protein Intake for Body Composition$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$High-Protein Intake for Body Composition$n$)),
  $a$Morton, Murphy, McKellar, et al.$a$,
  2018,
  $t$A systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength in healthy adults$t$,
  $j$British Journal of Sports Medicine$j$,
  $d$10.1136/bjsports-2017-097608$d$,
  $u$https://doi.org/10.1136/bjsports-2017-097608$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$High-Protein Intake for Body Composition$n$)),
  $a$Nunes, Colenso-Semple, McKellar, et al.$a$,
  2022,
  $t$Systematic review and meta-analysis of protein intake to support muscle mass and function in healthy adults$t$,
  $j$Journal of Cachexia, Sarcopenia and Muscle$j$,
  $d$10.1002/jcsm.12922$d$,
  $u$https://doi.org/10.1002/jcsm.12922$u$
);

-- Citations for: Peri-Workout Protein for Muscle Protein Synthesis
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Peri-Workout Protein for Muscle Protein Synthesis$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Peri-Workout Protein for Muscle Protein Synthesis$n$)),
  $a$Schoenfeld, Aragon, Krieger$a$,
  2013,
  $t$The effect of protein timing on muscle strength and hypertrophy: a meta-analysis$t$,
  $j$Journal of the International Society of Sports Nutrition$j$,
  $d$10.1186/1550-2783-10-53$d$,
  $u$https://doi.org/10.1186/1550-2783-10-53$u$
);

-- Citations for: Early Time-Restricted Eating for Insulin Sensitivity
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Early Time-Restricted Eating for Insulin Sensitivity$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Early Time-Restricted Eating for Insulin Sensitivity$n$)),
  $a$Sutton, Beyl, Early, Cefalu, Ravussin, Peterson$a$,
  2018,
  $t$Early Time-Restricted Feeding Improves Insulin Sensitivity, Blood Pressure, and Oxidative Stress Even without Weight Loss in Men with Prediabetes$t$,
  $j$Cell Metabolism$j$,
  $d$10.1016/j.cmet.2018.04.010$d$,
  $u$https://doi.org/10.1016/j.cmet.2018.04.010$u$
);

-- Citations for: Creatine Monohydrate for Strength and Cognition
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Creatine Monohydrate for Strength and Cognition$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Creatine Monohydrate for Strength and Cognition$n$)),
  $a$Prokopidis, Giannos, Triantafyllidis, Kechagias, Forbes, Candow$a$,
  2023,
  $t$Effects of creatine supplementation on memory in healthy individuals: a systematic review and meta-analysis of randomized controlled trials$t$,
  $j$Nutrition Reviews$j$,
  $d$10.1093/nutrit/nuac064$d$,
  $u$https://doi.org/10.1093/nutrit/nuac064$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Creatine Monohydrate for Strength and Cognition$n$)),
  $a$Xu, Bi, Zhang, Luo$a$,
  2024,
  $t$The effects of creatine supplementation on cognitive function in adults: a systematic review and meta-analysis$t$,
  $j$Frontiers in Nutrition$j$,
  $d$10.3389/fnut.2024.1424972$d$,
  $u$https://doi.org/10.3389/fnut.2024.1424972$u$
);

-- Citations for: Omega-3 EPA/DHA for Cardiovascular Health
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Omega-3 EPA/DHA for Cardiovascular Health$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Omega-3 EPA/DHA for Cardiovascular Health$n$)),
  $a$Bernasconi, Wiest, Lavie, Milani, Laukkanen$a$,
  2021,
  $t$Effect of Omega-3 Dosage on Cardiovascular Outcomes: An Updated Meta-Analysis and Meta-Regression of Interventional Trials$t$,
  $j$Mayo Clinic Proceedings$j$,
  $d$10.1016/j.mayocp.2020.08.034$d$,
  $u$https://doi.org/10.1016/j.mayocp.2020.08.034$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Omega-3 EPA/DHA for Cardiovascular Health$n$)),
  $a$Khan, Lone, Khan, et al.$a$,
  2021,
  $t$Effect of omega-3 fatty acids on cardiovascular outcomes: A systematic review and meta-analysis$t$,
  $j$eClinicalMedicine$j$,
  $d$10.1016/j.eclinm.2021.100997$d$,
  $u$https://doi.org/10.1016/j.eclinm.2021.100997$u$
);

-- Citations for: Vitamin D3 for Immune Function and Cancer Mortality Reduction
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Vitamin D3 for Immune Function and Cancer Mortality Reduction$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Vitamin D3 for Immune Function and Cancer Mortality Reduction$n$)),
  $a$Zhang, Fang, Tang, Jia, Feng, Xu, Faramand$a$,
  2019,
  $t$Association between vitamin D supplementation and mortality: systematic review and meta-analysis$t$,
  $j$BMJ$j$,
  $d$10.1136/bmj.l4673$d$,
  $u$https://doi.org/10.1136/bmj.l4673$u$
);

-- Citations for: Magnesium Supplementation for Sleep Quality
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Magnesium Supplementation for Sleep Quality$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Magnesium Supplementation for Sleep Quality$n$)),
  $a$Abbasi, Kimiagar, Sadeghniiat, Shirazi, Hedayati, Rashidkhani$a$,
  2012,
  $t$The effect of magnesium supplementation on primary insomnia in elderly: A double-blind placebo-controlled clinical trial$t$,
  $j$Journal of Research in Medical Sciences$j$,
  null,
  $u$https://pmc.ncbi.nlm.nih.gov/articles/PMC3703169/$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Magnesium Supplementation for Sleep Quality$n$)),
  $a$Mah, Pitre$a$,
  2021,
  $t$Oral magnesium supplementation for insomnia in older adults: a Systematic Review & Meta-Analysis$t$,
  $j$BMC Complementary Medicine and Therapies$j$,
  $d$10.1186/s12906-021-03297-z$d$,
  $u$https://doi.org/10.1186/s12906-021-03297-z$u$
);

-- Citations for: Ashwagandha Root Extract for Stress and Cortisol Reduction
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Ashwagandha Root Extract for Stress and Cortisol Reduction$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Ashwagandha Root Extract for Stress and Cortisol Reduction$n$)),
  $a$Chandrasekhar, Kapoor, Anishetty$a$,
  2012,
  $t$A prospective, randomized double-blind, placebo-controlled study of safety and efficacy of a high-concentration full-spectrum extract of ashwagandha root in reducing stress and anxiety in adults$t$,
  $j$Indian Journal of Psychological Medicine$j$,
  $d$10.4103/0253-7176.106022$d$,
  $u$https://doi.org/10.4103/0253-7176.106022$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Ashwagandha Root Extract for Stress and Cortisol Reduction$n$)),
  $a$Salve, Pate, Debnath, Langade$a$,
  2019,
  $t$Adaptogenic and Anxiolytic Effects of Ashwagandha Root Extract in Healthy Adults: A Double-blind, Randomized, Placebo-controlled Clinical Study$t$,
  $j$Cureus$j$,
  $d$10.7759/cureus.6466$d$,
  $u$https://doi.org/10.7759/cureus.6466$u$
);

-- Citations for: Mindfulness-Based Stress Reduction Program
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Mindfulness-Based Stress Reduction Program$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Mindfulness-Based Stress Reduction Program$n$)),
  $a$Khoury, Sharma, Rush, Fournier$a$,
  2015,
  $t$Mindfulness-based stress reduction for healthy individuals: A meta-analysis$t$,
  $j$Journal of Psychosomatic Research$j$,
  $d$10.1016/j.jpsychores.2015.03.009$d$,
  $u$https://doi.org/10.1016/j.jpsychores.2015.03.009$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Mindfulness-Based Stress Reduction Program$n$)),
  $a$Galante, et al.$a$,
  2023,
  $t$Systematic review and individual participant data meta-analysis of randomized controlled trials assessing mindfulness-based programs for mental health promotion$t$,
  $j$Nature Mental Health$j$,
  $d$10.1038/s44220-023-00081-5$d$,
  $u$https://doi.org/10.1038/s44220-023-00081-5$u$
);

-- Citations for: Guided Body Scan Deep Relaxation
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Guided Body Scan Deep Relaxation$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Guided Body Scan Deep Relaxation$n$)),
  $a$Moszeik, von Oertzen, Renner$a$,
  2022,
  $t$Effectiveness of a short Yoga Nidra meditation on stress, sleep, and well-being in a large and diverse sample$t$,
  $j$Current Psychology$j$,
  $d$10.1007/s12144-020-01042-2$d$,
  $u$https://doi.org/10.1007/s12144-020-01042-2$u$
);

-- Citations for: Cyclic Sighing Breathwork for Mood Enhancement
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Cyclic Sighing Breathwork for Mood Enhancement$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Cyclic Sighing Breathwork for Mood Enhancement$n$)),
  $a$Balban, Neri, Kogon, Weed, Nouriani, Jo, Holl, Zeitzer, Spiegel, Huberman$a$,
  2023,
  $t$Brief structured respiration practices enhance mood and reduce physiological arousal$t$,
  $j$Cell Reports Medicine$j$,
  $d$10.1016/j.xcrm.2022.100895$d$,
  $u$https://doi.org/10.1016/j.xcrm.2022.100895$u$
);

-- Citations for: Structured Gratitude Journaling for Well-Being
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Structured Gratitude Journaling for Well-Being$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Structured Gratitude Journaling for Well-Being$n$)),
  $a$Emmons, McCullough$a$,
  2003,
  $t$Counting blessings versus burdens: An experimental investigation of gratitude and subjective well-being in daily life$t$,
  $j$Journal of Personality and Social Psychology$j$,
  $d$10.1037/0022-3514.84.2.377$d$,
  $u$https://doi.org/10.1037/0022-3514.84.2.377$u$
);

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Structured Gratitude Journaling for Well-Being$n$)),
  $a$Malouff, Meynadier$a$,
  2023,
  $t$The effect of expressed gratitude interventions on psychological wellbeing: A meta-analysis of randomised controlled studies$t$,
  $j$International Journal of Applied Positive Psychology$j$,
  $d$10.1007/s41042-023-00086-6$d$,
  $u$https://doi.org/10.1007/s41042-023-00086-6$u$
);

-- Citations for: Focused Attention Meditation for Cognitive Enhancement
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Focused Attention Meditation for Cognitive Enhancement$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Focused Attention Meditation for Cognitive Enhancement$n$)),
  $a$Zainal, Newman$a$,
  2024,
  $t$Mindfulness enhances cognitive functioning: A meta-analysis of 111 randomized controlled trials$t$,
  $j$Health Psychology Review$j$,
  $d$10.1080/17437199.2023.2248222$d$,
  $u$https://doi.org/10.1080/17437199.2023.2248222$u$
);

-- Citations for: 14°C Cold Water Immersion for Catecholamine Response
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$14°C Cold Water Immersion for Catecholamine Response$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$14°C Cold Water Immersion for Catecholamine Response$n$)),
  $a$Srámek, Šimečková, Janský, Savlíková, Vybíral$a$,
  2000,
  $t$Human physiological responses to immersion into water of different temperatures$t$,
  $j$European Journal of Applied Physiology$j$,
  $d$10.1007/s004210050065$d$,
  $u$https://doi.org/10.1007/s004210050065$u$
);

-- Citations for: Post-Exercise Cold Water Immersion for Soreness and Recovery
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Cold Water Immersion for Soreness and Recovery$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Cold Water Immersion for Soreness and Recovery$n$)),
  $a$Leeder, Gissane, et al.$a$,
  2012,
  $t$Cold water immersion and recovery from strenuous exercise: a meta-analysis$t$,
  $j$British Journal of Sports Medicine$j$,
  $d$10.1136/bjsports-2011-090061$d$,
  $u$https://doi.org/10.1136/bjsports-2011-090061$u$
);

-- Citations for: Daily Cold-Shower Finish for Sickness Absence Reduction
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Daily Cold-Shower Finish for Sickness Absence Reduction$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Daily Cold-Shower Finish for Sickness Absence Reduction$n$)),
  $a$Buijze, Siem, et al.$a$,
  2016,
  $t$The Effect of Cold Showering on Health and Work: A Randomized Controlled Trial$t$,
  $j$PLOS ONE$j$,
  $d$10.1371/journal.pone.0161749$d$,
  $u$https://doi.org/10.1371/journal.pone.0161749$u$
);

-- Citations for: Frequent Finnish Sauna Bathing for Cardiovascular Risk Reduction
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Frequent Finnish Sauna Bathing for Cardiovascular Risk Reduction$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Frequent Finnish Sauna Bathing for Cardiovascular Risk Reduction$n$)),
  $a$Laukkanen, Kunutsor, et al.$a$,
  2015,
  $t$Association Between Sauna Bathing and Fatal Cardiovascular and All-Cause Mortality Events$t$,
  $j$JAMA Internal Medicine$j$,
  $d$10.1001/jamainternmed.2014.8187$d$,
  $u$https://doi.org/10.1001/jamainternmed.2014.8187$u$
);

-- Citations for: Post-Exercise Sauna Bathing for Endurance Adaptation
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Sauna Bathing for Endurance Adaptation$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Sauna Bathing for Endurance Adaptation$n$)),
  $a$Scoon, Hopkins, et al.$a$,
  2007,
  $t$Effect of post-exercise sauna bathing on the endurance performance of competitive male runners$t$,
  $j$Journal of Science and Medicine in Sport$j$,
  $d$10.1016/j.jsams.2006.06.009$d$,
  $u$https://doi.org/10.1016/j.jsams.2006.06.009$u$
);

-- Citations for: Single-Session Whole-Body Hyperthermia for Depressive Symptoms
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Single-Session Whole-Body Hyperthermia for Depressive Symptoms$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Single-Session Whole-Body Hyperthermia for Depressive Symptoms$n$)),
  $a$Janssen, Lowry, et al.$a$,
  2016,
  $t$Whole-Body Hyperthermia for the Treatment of Major Depressive Disorder: A Randomized Clinical Trial$t$,
  $j$JAMA Psychiatry$j$,
  $d$10.1001/jamapsychiatry.2016.1031$d$,
  $u$https://doi.org/10.1001/jamapsychiatry.2016.1031$u$
);

-- Citations for: Zone 2 Continuous Endurance Training for Aerobic Base
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Zone 2 Continuous Endurance Training for Aerobic Base$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Zone 2 Continuous Endurance Training for Aerobic Base$n$)),
  $a$Helgerud, Høydal, et al.$a$,
  2007,
  $t$Aerobic high-intensity intervals improve VO2max more than moderate training$t$,
  $j$Medicine & Science in Sports & Exercise$j$,
  $d$10.1249/mss.0b013e3180304570$d$,
  $u$https://doi.org/10.1249/mss.0b013e3180304570$u$
);

-- Citations for: 4x4 Minute HIIT for VO2max
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$4x4 Minute HIIT for VO2max$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$4x4 Minute HIIT for VO2max$n$)),
  $a$Helgerud, Høydal, et al.$a$,
  2007,
  $t$Aerobic high-intensity intervals improve VO2max more than moderate training$t$,
  $j$Medicine & Science in Sports & Exercise$j$,
  $d$10.1249/mss.0b013e3180304570$d$,
  $u$https://doi.org/10.1249/mss.0b013e3180304570$u$
);

-- Citations for: Sprint Interval Training for Mitochondrial and Cardiometabolic Adaptation
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Sprint Interval Training for Mitochondrial and Cardiometabolic Adaptation$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Sprint Interval Training for Mitochondrial and Cardiometabolic Adaptation$n$)),
  $a$Burgomaster, Howarth, et al.$a$,
  2008,
  $t$Similar metabolic adaptations during exercise after low volume sprint interval and traditional endurance training in humans$t$,
  $j$The Journal of Physiology$j$,
  $d$10.1113/jphysiol.2007.142109$d$,
  $u$https://doi.org/10.1113/jphysiol.2007.142109$u$
);

-- Citations for: Progressive Full-Body Resistance Training for Strength and Functional Longevity
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Progressive Full-Body Resistance Training for Strength and Functional Longevity$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Progressive Full-Body Resistance Training for Strength and Functional Longevity$n$)),
  $a$Peterson, Rhea, et al.$a$,
  2010,
  $t$Resistance exercise for muscular strength in older adults: a meta-analysis$t$,
  $j$Ageing Research Reviews$j$,
  $d$10.1016/j.arr.2010.03.004$d$,
  $u$https://doi.org/10.1016/j.arr.2010.03.004$u$
);

-- Citations for: Morning Bright-Light Exposure for Circadian Alignment
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Morning Bright-Light Exposure for Circadian Alignment$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Morning Bright-Light Exposure for Circadian Alignment$n$)),
  $a$van Maanen, Meijer, et al.$a$,
  2016,
  $t$The effects of light therapy on sleep problems: A systematic review and meta-analysis$t$,
  $j$Sleep Medicine Reviews$j$,
  $d$10.1016/j.smrv.2015.08.009$d$,
  $u$https://doi.org/10.1016/j.smrv.2015.08.009$u$
);

-- Citations for: Evening Blue-Light Blocking to Improve Insomnia Symptoms
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Evening Blue-Light Blocking to Improve Insomnia Symptoms$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Evening Blue-Light Blocking to Improve Insomnia Symptoms$n$)),
  $a$Shechter, Kim, et al.$a$,
  2018,
  $t$Blocking nocturnal blue light for insomnia: A randomized controlled trial$t$,
  $j$Journal of Psychiatric Research$j$,
  $d$10.1016/j.jpsychires.2017.10.015$d$,
  $u$https://doi.org/10.1016/j.jpsychires.2017.10.015$u$
);

-- Citations for: Warm Bath or Shower 1-2 Hours Before Bed to Shorten Sleep Onset
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Warm Bath or Shower 1-2 Hours Before Bed to Shorten Sleep Onset$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Warm Bath or Shower 1-2 Hours Before Bed to Shorten Sleep Onset$n$)),
  $a$Haghayegh, Khoshnevis, et al.$a$,
  2019,
  $t$Before-bedtime passive body heating by warm shower or bath to improve sleep: A systematic review and meta-analysis$t$,
  $j$Sleep Medicine Reviews$j$,
  $d$10.1016/j.smrv.2019.04.008$d$,
  $u$https://doi.org/10.1016/j.smrv.2019.04.008$u$
);

-- Citations for: Sleep Restriction Therapy for Chronic Insomnia
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Sleep Restriction Therapy for Chronic Insomnia$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Sleep Restriction Therapy for Chronic Insomnia$n$)),
  $a$Maurer, Espie, et al.$a$,
  2021,
  $t$The clinical effects of sleep restriction therapy for insomnia: A meta-analysis of randomised controlled trials$t$,
  $j$Sleep Medicine Reviews$j$,
  $d$10.1016/j.smrv.2021.101493$d$,
  $u$https://doi.org/10.1016/j.smrv.2021.101493$u$
);

-- Citations for: Early Time-Restricted Eating Window for Insulin Sensitivity
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Early Time-Restricted Eating Window for Insulin Sensitivity$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Early Time-Restricted Eating Window for Insulin Sensitivity$n$)),
  $a$Sutton, Beyl, et al.$a$,
  2018,
  $t$Early Time-Restricted Feeding Improves Insulin Sensitivity, Blood Pressure, and Oxidative Stress Even without Weight Loss in Men with Prediabetes$t$,
  $j$Cell Metabolism$j$,
  $d$10.1016/j.cmet.2018.04.010$d$,
  $u$https://doi.org/10.1016/j.cmet.2018.04.010$u$
);

-- Citations for: Mediterranean Dietary Pattern With Olive Oil or Nuts for Cardiovascular Prevention
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Mediterranean Dietary Pattern With Olive Oil or Nuts for Cardiovascular Prevention$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Mediterranean Dietary Pattern With Olive Oil or Nuts for Cardiovascular Prevention$n$)),
  $a$Estruch, Ros, et al.$a$,
  2013,
  $t$Primary Prevention of Cardiovascular Disease with a Mediterranean Diet$t$,
  $j$The New England Journal of Medicine$j$,
  $d$10.1056/NEJMoa1200303$d$,
  $u$https://doi.org/10.1056/NEJMoa1200303$u$
);

-- Citations for: Post-Exercise Carbohydrate+Protein Feeding for Glycogen Recovery
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Carbohydrate+Protein Feeding for Glycogen Recovery$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Post-Exercise Carbohydrate+Protein Feeding for Glycogen Recovery$n$)),
  $a$Ivy, Goforth, et al.$a$,
  2002,
  $t$Early postexercise muscle glycogen recovery is enhanced with a carbohydrate-protein supplement$t$,
  $j$Journal of Applied Physiology$j$,
  $d$10.1152/japplphysiol.00394.2002$d$,
  $u$https://doi.org/10.1152/japplphysiol.00394.2002$u$
);

-- Citations for: Nightly Magnesium Supplementation for Primary Insomnia
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Nightly Magnesium Supplementation for Primary Insomnia$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Nightly Magnesium Supplementation for Primary Insomnia$n$)),
  $a$Abbasi, Kimiagar, et al.$a$,
  2012,
  $t$The effect of magnesium supplementation on primary insomnia in elderly: A double-blind placebo-controlled clinical trial$t$,
  $j$Journal of Research in Medical Sciences$j$,
  null,
  $u$https://pmc.ncbi.nlm.nih.gov/articles/PMC3703169/$u$
);

-- Citations for: Daily Creatine Monohydrate for Strength and Lean Mass
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Daily Creatine Monohydrate for Strength and Lean Mass$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Daily Creatine Monohydrate for Strength and Lean Mass$n$)),
  $a$Kreider, Kalman, et al.$a$,
  2017,
  $t$International Society of Sports Nutrition position stand: safety and efficacy of creatine supplementation in exercise, sport, and medicine$t$,
  $j$Journal of the International Society of Sports Nutrition$j$,
  $d$10.1186/s12970-017-0173-z$d$,
  $u$https://doi.org/10.1186/s12970-017-0173-z$u$
);

-- Citations for: Daily Omega-3 EPA+DHA for Lipid and Cardiovascular Risk Markers
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Daily Omega-3 EPA+DHA for Lipid and Cardiovascular Risk Markers$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Daily Omega-3 EPA+DHA for Lipid and Cardiovascular Risk Markers$n$)),
  $a$Choi, Calder, et al.$a$,
  2024,
  $t$The differential effects of eicosapentaenoic acid and docosahexaenoic acid on cardiovascular risk factors: an updated systematic review of randomized controlled trials$t$,
  $j$Frontiers in Nutrition$j$,
  $d$10.3389/fnut.2024.1423228$d$,
  $u$https://doi.org/10.3389/fnut.2024.1423228$u$
);

-- Citations for: Ashwagandha Root Extract for Stress and Anxiety Reduction
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Ashwagandha Root Extract for Stress and Anxiety Reduction$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Ashwagandha Root Extract for Stress and Anxiety Reduction$n$)),
  $a$Chandrasekhar, Kapoor, et al.$a$,
  2012,
  $t$A Prospective, Randomized Double-Blind, Placebo-Controlled Study of Safety and Efficacy of a High-Concentration Full-Spectrum Extract of Ashwagandha Root in Reducing Stress and Anxiety in Adults$t$,
  $j$Indian Journal of Psychological Medicine$j$,
  $d$10.4103/0253-7176.106022$d$,
  $u$https://doi.org/10.4103/0253-7176.106022$u$
);

-- Citations for: Mindfulness-Based Stress Reduction Daily Practice
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Mindfulness-Based Stress Reduction Daily Practice$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Mindfulness-Based Stress Reduction Daily Practice$n$)),
  $a$Grossman, Niemann, et al.$a$,
  2004,
  $t$Mindfulness-based stress reduction and health benefits. A meta-analysis$t$,
  $j$Journal of Psychosomatic Research$j$,
  $d$10.1016/S0022-3999(03)00573-7$d$,
  $u$https://doi.org/10.1016/S0022-3999(03)00573-7$u$
);

-- Citations for: Cyclic Sighing Breathwork for Acute Mood and Arousal Reduction
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Cyclic Sighing Breathwork for Acute Mood and Arousal Reduction$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Cyclic Sighing Breathwork for Acute Mood and Arousal Reduction$n$)),
  $a$Balban, Neri, et al.$a$,
  2023,
  $t$Brief structured respiration practices enhance mood and reduce physiological arousal$t$,
  $j$Cell Reports Medicine$j$,
  $d$10.1016/j.xcrm.2022.100895$d$,
  $u$https://doi.org/10.1016/j.xcrm.2022.100895$u$
);

-- Citations for: Structured Gratitude Journaling for Well-Being
DELETE FROM public.research_citations
WHERE protocol_id = (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Structured Gratitude Journaling for Well-Being$n$));

INSERT INTO public.research_citations (protocol_id, authors, year, title, journal, doi, url)
VALUES (
  (SELECT id FROM public.protocols WHERE lower(name) = lower($n$Structured Gratitude Journaling for Well-Being$n$)),
  $a$Emmons, McCullough$a$,
  2003,
  $t$Counting Blessings Versus Burdens: An Experimental Investigation of Gratitude and Subjective Well-Being in Daily Life$t$,
  $j$Journal of Personality and Social Psychology$j$,
  $d$10.1037/0022-3514.84.2.377$d$,
  $u$https://doi.org/10.1037/0022-3514.84.2.377$u$
);

-- ============================================================================
-- VERIFICATION QUERIES (can be removed after testing)
-- ============================================================================
-- SELECT COUNT(*) as protocol_count FROM public.protocols;
-- SELECT COUNT(*) as citation_count FROM public.research_citations;
-- SELECT p.name, COUNT(c.id) as citations
--   FROM public.protocols p
--   LEFT JOIN public.research_citations c ON c.protocol_id = p.id
--   GROUP BY p.id, p.name
--   ORDER BY p.name;
